# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Exercícios</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

#### <span style="color:red">Recomenda-se fortemente que os exercícios sejam feitos sem consultar as respostas antecipadamente.</span>

In [18]:
import numpy as np

### Exercício 1)
Utilize comprehension para gerar a lista de todos os números interios entre 0 e 19. Converta a lista em um <font color='blue'>numpy</font> array bidimensional (matriz) com 4 linhas e 5 colunas.

In [4]:
numeros = np.array( [x for x in range(0, 20)] ).reshape((4, 5))
numeros

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### Exercício 2)
Construa um array unidimensional com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. Reformate o array para que se torne uma matriz `A` com 5 linhas e 6 colunas.

In [5]:
numeros2 = np.random.randint(0, 20, 30).reshape((5, 6))
print(numeros2)

[[19  0  4 11  4 11]
 [ 0 14  0 13 12 18]
 [13  3 14 14 14 14]
 [ 1 10 14  7 15 18]
 [17  1  9  8 14  4]]


### Exercício 3)
Crie uma __view__ da matriz `A` gerada na célula anterior contendo:
- as linhas de `A` com índices 0,1 e 3
- as linhas de `A` com índice 1 e 2 e as colunas com índice 0,2 e 4
- as linhas de `A` com índice 1 e 3 e as colunas com índice 1 e 3

In [12]:
v1 = numeros2[[0, 1, 3]]
v2 = numeros2[0:3, [0, 2, 4]]
v3 = numeros2[[1, 3]][:,[1, 3]]
print(v1)
print(v2)
print(v3)


[[19  0  4 11  4 11]
 [ 0 14  0 13 12 18]
 [ 1 10 14  7 15 18]]
[[19  4  4]
 [ 0  0 12]
 [13 14 14]]
[[14 13]
 [10  7]]


### Exercício 4)
Construa um array `A` bidimensional 5x6 com 30 números inteiros escolhidos de forma randômica no intervalo entre 0 e 20. 
- faça uma cópia do array `A` criado, chamando a cópia de `Ac`
- Substitua todos os elementos do array `A` que sejam maiores que 10 pelo valor -1 
- Substitua todos os elementos do array `Ac` que sejam maiores que 7 e menores que 15 pelo valor -1 

__Dica:__ Gere máscaras booleanas para realizar as modificações nos arrays.

In [36]:
A = np.random.randint(0, 20, 30).reshape((5, 6))
Ac = np.copy(A)
print(Ac)

A[A > 10] = -1
print(A)

Ac[(Ac > 7) & (Ac > 15)] = -1
print(Ac)



[[15  4 14  6  1 11]
 [16 14  0  5 19  1]
 [ 0 12  7 16  5  3]
 [ 1  9 17  6 11  2]
 [17  9  7 11  9 18]]
[[-1  4 -1  6  1 -1]
 [-1 -1  0  5 -1  1]
 [ 0 -1  7 -1  5  3]
 [ 1  9 -1  6 -1  2]
 [-1  9  7 -1  9 -1]]
[[15  4 14  6  1 11]
 [-1 14  0  5 -1  1]
 [ 0 12  7 -1  5  3]
 [ 1  9 -1  6 11  2]
 [-1  9  7 11  9 -1]]


### Exercício 5)
Construa um array `A` com 20 linhas e 10 colunas onde os elementos são os números interios de  1 até 200.
- Crie uma __view__ de `A` chamada `A_lpares` contendo apenas as linhas de `A` com índice par. 
- Crie uma __view__ de `A` chamada `A_lpares_cimpares` contendo as linhas `A` com índice par e colunas com índice ímpar. 

In [61]:
A = np.arange(1, 201).reshape((20, 10))
print(A)

A_lpares = A[np.arange(A.shape[0]) % 2 == 0]
print(A_lpares)

A_lpares_cimpares = A_lpares[:, np.arange(A.shape[1]) % 2 == 1]
print(A_lpares_cimpares)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]
 [101 102 103 104 105 106 107 108 109 110]
 [111 112 113 114 115 116 117 118 119 120]
 [121 122 123 124 125 126 127 128 129 130]
 [131 132 133 134 135 136 137 138 139 140]
 [141 142 143 144 145 146 147 148 149 150]
 [151 152 153 154 155 156 157 158 159 160]
 [161 162 163 164 165 166 167 168 169 170]
 [171 172 173 174 175 176 177 178 179 180]
 [181 182 183 184 185 186 187 188 189 190]
 [191 192 193 194 195 196 197 198 199 200]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 61  62 

### Exercício 6)
Substitua os elememtos do array `A` do exercício anterior por -1 quando pelo menos um dos índices do elemento é par. 

__Dica:__ Construa uma máscara booleana

In [65]:
mask = [x%2==0 or y%2==0 for x in range(A.shape[0]) for y in range(A.shape[1])]
mask = np.array(mask).reshape(A.shape)
print(mask)
A[mask] = -1
print(A)

[[ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True False]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True False  True False  True False  True False  True

### Exercício 7)
Considere o array `X` de números tipo <font color='blue'>float</font> gerado a partir de uma distribuição uniforme no intervalo entre 0 e 1. Escreva um código para encontrar os três menores valores do array.

__Dica:__ Converta o array em uma lista e ordene.

### Exercício 8)
Escreva uma função chamada `troca_colunas` que recebe um array e o índice de duas colunas como parâmetros e retorna o array com as colunas trocadas. Por exemplo:
```python
X = np.array([[0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5], 
              [0, 1, 2, 3, 4, 5]])

X = troca_colunas(X,1,3)
print(X)
```
deve resultar em
```python
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]
```


In [67]:
def troca_colunas(A,i,j):
    # inclua se codigo aqui
    Acol = np.copy(A[:, [i, j]])
    A[:, i] = Acol[:, 1]
    A[:, j] = Acol[:, 0]
    return(A)

X = np.array([[0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5], [0, 1, 2, 3, 4, 5]])
print(X)

X = troca_colunas(X,1,3)
print(X)

[[0 1 2 3 4 5]
 [0 1 2 3 4 5]
 [0 1 2 3 4 5]]
[[0 3 2 1 4 5]
 [0 3 2 1 4 5]
 [0 3 2 1 4 5]]


### Exercício 9)
Os métodos <font color='blue'>vstack</font> e <font color='blue'>hstack</font> do <font color='blue'>numpy</font> empilha matrizes na vertical e horizontal, respectivamente. Por exemplo:
```python
A = [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
B = [[2.0, 2.0, 2.0], [2.0, 2.0, 2.0]]

C = np.vstack((A,B))
print(C)
```
resulta em
```python
[[1. 1. 1.]
 [1. 1. 1.]
 [2. 2. 2.]
 [2. 2. 2.]]
```
Escreva um código para gerar duas matrizes `A` e `B` de números inteiros randômicos no intervalo entre 0 e 10, onde:
- A matriz `A` é 5x6
- A matriz `B` é 5x3

Utilize o método <font color='blue'>hstack</font> para empilhar as matrizes

O que acontece se tentar utilizar o método <font color='blue'>vstack</font>? Explique o motivo da mensagem gerada.

In [71]:
A = np.random.randint(0, 10, 30).reshape((5,6))
B = np.random.randint(0, 10, 15).reshape((5,3))
C = np.hstack((A, B))
print(C)

D = np.vstack((A, B))

[[4 9 2 6 5 6 2 7 7]
 [9 2 1 2 4 1 3 0 8]
 [8 8 8 7 2 4 9 3 1]
 [0 3 2 6 3 4 6 2 1]
 [0 4 9 0 8 7 6 7 4]]


ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 6 and the array at index 1 has size 3

### Exercício 10)
Escreva um código para, data uma matriz, zerar todos os elementos abaixo da diagonal principal da matriz. Por exemplo:
```python
[[2 8 3 4 8]
 [4 8 7 7 3]
 [8 2 3 1 4]
 [8 6 3 8 1]
 [6 4 4 6 1]]
```
deve resultar em
```python
[[2 8 3 4 8]
 [0 8 7 7 3]
 [0 0 3 1 4]
 [0 0 0 8 1]
 [0 0 0 0 1]]
```

In [77]:
A = np.random.randint(1, 100, 100).reshape((10,10))
print (A)

A[np.array([l > c for l in range(A.shape[0]) for c in range(A.shape[1])]).reshape(A.shape)] = 0
print(A)

[[53 28 97 27 53 40  3 34 65 52]
 [54 66 25  1 40 29 66 30 68 63]
 [31 15 87 24 73 42 27 44 48 39]
 [67 61 83 21 40 68 76 93 36 44]
 [98 39 47 27 19 92 93 45 28 61]
 [24  9  8  1 71 95 43 30 27 65]
 [32 23  2  4 50 49 98 11 37 16]
 [ 2 53 74 18 38 70 95 65 53 16]
 [42 88 75 10 87  1 25 20 81 25]
 [82 94 63  2 35 51 88 53 92  2]]
[[53 28 97 27 53 40  3 34 65 52]
 [ 0 66 25  1 40 29 66 30 68 63]
 [ 0  0 87 24 73 42 27 44 48 39]
 [ 0  0  0 21 40 68 76 93 36 44]
 [ 0  0  0  0 19 92 93 45 28 61]
 [ 0  0  0  0  0 95 43 30 27 65]
 [ 0  0  0  0  0  0 98 11 37 16]
 [ 0  0  0  0  0  0  0 65 53 16]
 [ 0  0  0  0  0  0  0  0 81 25]
 [ 0  0  0  0  0  0  0  0  0  2]]
